services: 
  messages-db:
      container_name: messages_db
      image: postgres:14.3
      restart: always
      volumes:
        - ./postgres:/var/lib/postgres/data
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}